#!/bin/sh

site=".cabal-sandbox/bin/siphilia.net"

HELP=
if [ "$1" == "html" ]; then
    $site build
elif [ "$1" == "rebuild" ]; then
    $site rebuild
elif [ "$1" == "deploy" ]; then
    $site deploy
elif [ "$1" == "clean" ]; then
    $site clean
elif [ "$1" == "preview" ]; then
    $site preview
elif [ "$1" == "site" ]; then
    cabal install --reorder-goals
else
    cat <<_EOF_
build html
    $site build

build rebuild
    $site rebuild

build deploy
    $site deploy

build clean
    $site clean

build preview
    $site preview

build site
    cabal install
_EOF_
fi