name: siphilia-github-io
version: '0.1.0.0'
author: sifyfy
maintainer: sifyfy@sifyfy.dev
copyright: (c) 2013-2019 sifyfy.
license: AllRightsReserved
dependencies:
- base == 4.*
- binary
- filepath
- hakyll == 4.*
- process
- pandoc
executables:
  site:
    main: site.hs
    ghc-options:
      - -threaded
